name: Build and Push to Azure Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: dockerzwol.azurecr.io
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t dockerzwol.azurecr.io/myreact:latest .
        docker push dockerzwol.azurecr.io/myreact:latest

        
  ssh-actions:
    needs: build-and-push
    runs-on: ubuntu-latest
   
    steps:
    - name: Copy Docker Compose file to VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_SSH_HOST }}
        username: ${{ secrets.VM_SSH_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: ${{ secrets.VM_SSH_PORT }}
        source: "./docker-compose.yml"
        target: "/home/coalkid/docker/"
        
    - name: SSH into VM and update Docker Compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_SSH_HOST }}
        username: ${{ secrets.VM_SSH_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: ${{ secrets.VM_SSH_PORT }}
        script: |
          cd /home/coalkid/docker
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up -d
